### ISSUE TITLE
TypeError: must be unicode, not str

### ISSUE THREAD

**Issue by aclark4life** [collective/transmogrify.siteanalyser#2]
Got this trying to funnelweb blog.aclark.net:

```
INFO:crawler:Crawling: http://blog.aclark.net/wp-content/uploads/2011/08/Screen-Shot-2011-08-28-at-8.09.00-PM.png
INFO:titleguess(pathsorter):104 folders added. 0 defaultpages set, 541 items sorted
Traceback (most recent call last):
  File "bin/funnelweb", line 119, in <module>
    mr.migrator.runner.runner({},"funnelweb.remote")
  File "/Users/aclark/Developer/eggs-directory/mr.migrator-1.0b10-py2.7.egg/mr/migrator/runner/__init__.py", line 174, in runner
    transmogrifier(pipelineid, **overrides)
  File "/Users/aclark/Developer/eggs-directory/collective.transmogrifier-1.3-py2.7.egg/collective/transmogrifier/transmogrifier.py", line 62, in __call__
    for item in pipeline:
  File "/Users/aclark/Developer/eggs-directory/transmogrify.webcrawler-1.0-py2.7.egg/transmogrify/webcrawler/staticcreator.py", line 42, in __iter__
    for item in self.previous:
  File "/Users/aclark/Developer/eggs-directory/transmogrify.ploneremote-1.0b6-py2.7.egg/transmogrify/ploneremote/remoteprune.py", line 80, in __iter__
    for item in self.previous:
  File "/Users/aclark/Developer/eggs-directory/transmogrify.ploneremote-1.0b6-py2.7.egg/transmogrify/ploneremote/remoteredirector.py", line 24, in __iter__
    for item in self.previous:
  File "/Users/aclark/Developer/eggs-directory/transmogrify.ploneremote-1.0b6-py2.7.egg/transmogrify/ploneremote/remoteworkflowupdater.py", line 34, in __iter__
    for item in self.previous:
  File "/Users/aclark/Developer/eggs-directory/collective.transmogrifier-1.3-py2.7.egg/collective/transmogrifier/sections/inserter.py", line 19, in __iter__
    for item in self.previous:
  File "/Users/aclark/Developer/eggs-directory/transmogrify.ploneremote-1.0b6-py2.7.egg/transmogrify/ploneremote/remotenavigationexcluder.py", line 30, in __iter__
    for item in self.previous:
  File "/Users/aclark/Developer/eggs-directory/transmogrify.ploneremote-1.0b6-py2.7.egg/transmogrify/ploneremote/remoteschemaupdater.py", line 31, in __iter__
    for item in self.previous:
  File "/Users/aclark/Developer/eggs-directory/transmogrify.ploneremote-1.0b6-py2.7.egg/transmogrify/ploneremote/remoteconstructor.py", line 35, in __iter__
    for item in self.previous:
  File "/Users/aclark/Developer/eggs-directory/transmogrify.pathsorter-1.0b4-py2.7.egg/transmogrify/pathsorter/treeserializer.py", line 23, in __iter__
    for item in self.previous:
  File "/Users/aclark/Developer/eggs-directory/collective.transmogrifier-1.3-py2.7.egg/collective/transmogrifier/sections/inserter.py", line 19, in __iter__
    for item in self.previous:
  File "/Users/aclark/Developer/eggs-directory/transmogrify.pathsorter-1.0b4-py2.7.egg/transmogrify/pathsorter/treeserializer.py", line 23, in __iter__
    for item in self.previous:
  File "/Users/aclark/Developer/eggs-directory/transmogrify.siteanalyser-1.0-py2.7.egg/transmogrify/siteanalyser/relinker.py", line 85, in __iter__
    newpath = '/'.join([norm(part) for part in path.split('/')])
  File "/Users/aclark/Developer/eggs-directory/transmogrify.siteanalyser-1.0-py2.7.egg/transmogrify/siteanalyser/relinker.py", line 80, in norm
    part = normalizer.normalize(**keywords)
  File "/Users/aclark/Developer/eggs-directory/transmogrify.siteanalyser-1.0-py2.7.egg/transmogrify/siteanalyser/external/normalize.py", line 176, in normalize
    text = baseNormalize(text)
  File "/Users/aclark/Developer/eggs-directory/transmogrify.siteanalyser-1.0-py2.7.egg/transmogrify/siteanalyser/external/base.py", line 71, in baseNormalize
    elif decomposition(ch):
TypeError: must be unicode, not str

```

**Comment by djay** [comment]
try using trunk.

**Comment by aclark4life** [comment]
i don't particularly want to use trunk, this is for documentation. if you move to collective i can cut a release though.

**Comment by djay** [comment]
I can move these to the collective.

**Comment by petri** [comment]
I ran into the same issue. At my end, the problem seems to be caused by a ™ (trademark) character, u2122 in unicode. 

What seems to happen is that  when transmogrify.siteanalyser receives it from server, encoded into its three-byte '\xe2\x84\xa2' UTF-8 encoded string representation, ittries to process it character by character. The \xe2 part corresponds to a valid character, but upon \x84 it barfs.

I did not dig deeper into the circumstances - but I suspect quite a few if not all three-byte unicode chars might cause the same problem?

**Comment by petri** [comment]
BTW, upon a superficial inspection, I did not see anything relevant in the trunk that would alleviate this problem since the latest release.

**Comment by petri** [comment]
Trying trunk, I get a zope.component.interfaces.ComponentLookupError: (<InterfaceClass collective.transmogrifier.interfaces.ISectionBlueprint>, u'transmogrify.siteanalyser.defaultpage') ...

**Comment by djay** [comment]
Looks like there a missed checkin. Stay tuned

Dylan Jay
Technical solution manager
PretaWeb 99552830

On 03/02/2012, at 6:24 PM, Petri Savolainen
reply@reply.github.com
wrote:

**Comment by djay** [comment]
everything checked in. Do you have a full traceback and the pipeline you're using?

**Comment by petri** [comment]
I tried getting the trunk again and now it works ok. Weird. Could be I stumbled on a conflict with some leftover eggs in the buildout cache, as I now did a clean buildout. My bad.
